GET http://localhost:2060/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6IkJsdWViZXJyeSIsImVtYWlsIjoic2VnYWdhd2EzMjIzMjMyMzMzMkBnbWFpbC5jb20iLCJpYXQiOjE3MjgyNDA5MjIsImV4cCI6MTcyODI0MTgyMn0.5gSi0KYaHg-Dl5a1Gmt3mNxuxzeZQLE0J41y2u9aMlA